name = "DiskDataProviders"
uuid = "09c11fbc-f0d5-45fc-84dd-4606816a719d"
authors = ["Fredrik Bagge Carlson <baggepinnen@gmail.com>"]
version = "0.1.0"

[deps]
LearnBase = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
MLDataUtils = "cc2ba9b6-d476-5e6d-8eaf-a92d5412d41d"
